### ISSUE TITLE
Pi-hole - No Response

### ISSUE THREAD

**Issue by MED1975** [arendruni/homebridge-pihole#1] opened 2019-11-04 22:26 UTC
Hi there - I cannot get this to work. Running Homebridge. Only one other plugin for Nest. Following creating the config.json file and restarting Homebridge this plugin (or my config) causes the Nest plugin to stop work. The Pi-hole appears in Apple Home and switches between updating and no response.

Additionally when running with your plugin my Nest account keeps email me to say a new sign in detected, so presumably something keeps restarting.

Config file:

{
    "bridge": {
        "name": "Homebridge",
        "username": "******",
        "port": 51826,
        "pin": "***-**-***"
    },
    "description": "blah": [
        {
            "accessory": "Pihole",
            "name": "Pi-hole",
            "auth": "32c9922b727***********85d54b2e0c7018aba490e655082a",
            "host": "192.168.1.10"
        }
            ],
    "platforms": [
        {
            "platform": "Nest",
            "email": "*********",
            "password": "***********",
            "options": [
                "Thermostat.Fan.Disable"
            ]
        }
    ]
}

When your plugin is running this line appears in the logs

[11/4/2019, 8:47:08 PM] Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)

Any ideas? Thanks for developing this plugin. I look forward to being able to disable the Pihole using the HomeKit framework - will be great for the family to be able to disable it!

**Comment by arendruni** [comment] 2019-11-23 23:16
May be related to #2

**Comment by arendruni** [comment] 2019-11-23 23:16
Duplicate of #2

**Closed by arendruni** 2019-11-23 23:16 UTC

**Comment by coalfield** [comment] 2019-11-24 06:45
Seeing the same issue think this would need to be reopened?

**Comment by MED1975** [comment] 2019-11-27 13:25
Hi - just to say since the last update this is working perfectly. Thanks.

**Comment by coalfield** [comment] 2019-11-27 14:46
Ditto that
