### ISSUE TITLE
[BUG] Pi-hole switch always in 'off' mode.

### ISSUE THREAD

**Issue by PatriceRobert** [arendruni/homebridge-pihole#46] opened 2022-01-09 07:51 UTC
Pi-hole switch always in position 'Off' in homekit.

1. Pi-hole switch showing 'Off' on the home app
2. Click to turn it on
3. Check it is really 'On' under the Pi-hole console (check both states)
4. quit and re-connect to the home app
5. Pi-hole switch is 'Off'

The actions are well executed via API so connection is ok, API key is correct and working fine, the only issue is to see the Pi-hole switch back to 'Off' all the time.
This is happening since the latest Pi-hole update running under docker:
 - Docker Tag 2022.01.1
 - Pi-hole v5.8.1
 - FTL v5.13
 - Web Interface v5.10.1
 - MacOS 12.1 / iOS 15.2

No a big issue as it's still working but annoying as we cannot get the correct state and it can break some automations.

**Comment by arendruni** [comment] 2022-01-09 14:08
Hi @PatriceRobert, you're not the only reporting this issue as other users are experiencing this bug with the latest pi-hole versions. 
I investigated and found out that the plugins is working as expected, in fact the bug is on the pi-hole admin: the status request used by the plugin is always returning `{"status":"disabled"}`. See pi-hole/AdminLTE#2051 for more informations, a fix will be added in their next release.

I am leaving this issue open as a spike.

**Comment by jamie-2bit** [comment] 2022-01-23 09:23
Yes, finding this is the case also on Pi-hole v5.8.1 FTL v5.13 Web Interface v5.10.1

**Comment by AquaRelliux** [comment] 2022-01-23 12:05
haha I just spent 1-2 hours trying to get this to work my toggle was always set to disabled even though pihole was enabled. I am guessing this bug is still active? Because otherwise this is not working at all for me it works in homeassistant with their plugin flawlessly but I am trying to go away from homeassistant because it is just to much hassle to get it to work

**Comment by g6nhu** [comment] 2022-01-30 15:06
I rebuilt my homebridge as hoobs this morning and have spent hours trying to sort this!

**Comment by AquaRelliux** [comment] 2022-01-30 22:04
> I rebuilt my homebridge as hoobs this morning and have spent hours trying to sort this!

Ye it sucks it works perfect in homeassistant though so I guess it is coded better in there

**Comment by jamie-2bit** [comment] 2022-02-01 08:57
Any updates on this one? Has Pihole indicated a bug fix release date yet?

**Comment by rloomans** [comment] 2022-02-05 03:08
I've created a pull request that works around the Pihole bug: #49

**Comment by arendruni** [comment] 2022-02-07 20:42
Hi everyone, and thank for the support! 
I've just [released](https://github.com/arendruni/homebridge-pihole/releases/tag/v0.4.2-beta.0) a beta version `v0.4.2-beta.0` with @rloomans patch using the main API, the different endpoint introduced by #49, seems to cache the old `status` value for 15-20 seconds before updating it, so I'm keeping this in beta before releasing to the main channel, probably next week.

**Comment by vinaydawani** [comment] 2022-02-13 17:17
I had been running the same issue but it seems to be fixed in Pi-hole [v5.9](https://github.com/pi-hole/pi-hole/releases/v5.9) FTL [v5.14](https://github.com/pi-hole/FTL/releases/v5.14) Web Interface [v5.11](https://github.com/pi-hole/AdminLTE/releases/v5.11)

Here's the update from [admin thread](https://github.com/pi-hole/AdminLTE/issues/2051#issuecomment-1037450716)

**Comment by arendruni** [comment] 2022-02-13 17:29
I can confirm the plugin is working correctly again on Pi-hole [v5.9](https://github.com/pi-hole/pi-hole/releases/v5.9) FTL [v5.14](https://github.com/pi-hole/FTL/releases/v5.14) Web Interface [v5.11](https://github.com/pi-hole/AdminLTE/releases/v5.11)

**Closed by arendruni** 2022-02-13 17:29 UTC
Labels: bug
