### ISSUE TITLE
[BUG] Homekit switch not changing pihole state anymore

### ISSUE THREAD

**Issue by buzz-dee81** [arendruni/homebridge-pihole#47] opened 2022-01-09 12:52 UTC
Since the latest update, the HomeKit switch does not change the active state of Pihole anymore. 

1. Go to Apple Home app
2. Click the Pihole switch (which deactivates Pihole for 1 min in my setup)
3. go to Pihole web Interfaxe an check for the status
4. Pihole is still active

 - OS: Raspbian GNU/Linux 10 (buster)
 - Pi-hole v5.8.1  
 - FTL v5.13  
 - Web Interface v5.10.1
 
 - Homebridge v 1.3.9
 - Node.js v16.13.1
 - npm v8.3.0

**Comment by arendruni** [comment] 2022-01-09 14:09
Hi @buzz-dee81! I'm closing this since is a duplicate of @46

**Closed by arendruni** 2022-01-09 14:09 UTC
Labels: bug

**Comment by buzz-dee81** [comment] 2022-01-09 14:21
Hi, 

thanks for the heads-up. I thought I read in #46 that it’s just the switch that does not reflect the state of Pihole anymore, but the actual switching on/off is still happening. On my end it doesn’t do the switching at all. 

Thanks 

Von meinem iPhone gesendet

**Comment by arendruni** [comment] 2022-01-09 15:29
Ok, I think both the issues are caused by the same bug in Pi-hole admin, let's wait for their next release and see if they are both fixed, if not the case you can reopen this issue.
